name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'


jobs:
  publish:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest  # Specify the runner environment
    steps:
    - uses: actions/checkout@v3  # Check out the repository code
   
    # This action adds a token needed for pub.dev
    - name: Set up Dart
      uses: dart-lang/setup-dart@v1  # Corrected the path for the Dart setup action

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        cache: true


    - name: Publish to pub.dev
      run: flutter pub publish --force